# Generated by Django 5.0.4 on 2024-06-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catogary',
            name='catogary_image',
            field=models.ImageField(upload_to='images/catagory'),
        ),
    ]
