# Generated by Django 5.0.4 on 2024-05-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_product_category_product_catogary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catogary',
            new_name='product_category',
        ),
    ]
